version: "3"
services:
  nestjs-api:
    image: tokenize-xchange
    env_file:
      - .env
    ports:
      - "9000:9000"
    networks:
      - tokenize-xchange
 
networks:
  tokenize-xchange:
    driver: bridge
    